project/Open/Soft/Controllers/RolesController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Open.Archetypes.RoleClasses;
using Open.Logic.RoleClasses;

namespace Open.Soft.Controllers {
    [HandleError]
    public class RolesController : Controller {
        public ActionResult Index() {
            var roleViewModels = (from role in Roles.Instance
                                  where role.IsActive
                                  select new RoleViewModel(role)).ToList();
            return View(roleViewModels);
        }

        public ActionResult Create() { return View(new RoleEditModel()); }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "Name,Description,Type")] RoleEditModel roleEditModel) {
            if (!ModelState.IsValid) return View("Create", roleEditModel);
            roleEditModel.Create();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(string id) {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return View(new RoleEditModel(id));
        }
        public ActionResult Details(string id) {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return View(new RoleViewModel(id));
        }

        public ActionResult Delete(string id) {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return View(new RoleViewModel(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, FormCollection collection) {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var roleEditModel = new RoleEditModel(id);
            roleEditModel.Delete();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "UniqueId,Name,Description,Type")] RoleEditModel roleEditModel) {
            if (!ModelState.IsValid) return View("Edit", roleEditModel);
            roleEditModel.Update(roleEditModel.UniqueId);
            return RedirectToAction("Index");
        }
    }
}

project/Open/Soft/Views/Roles/Create.cshtml
@model Open.Logic.RoleClasses.RoleEditModel

@{
    ViewBag.Title = "Create Role";
}

<h2>Create role</h2>

@using (Html.BeginForm("Create", "Roles", new { ID = Model.UniqueId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, Model.ActiveRoleTypes)
                @Html.ValidationMessageFor(model => model.ActiveRoleTypes, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

project/Open/Soft/Views/Roles/Delete.cshtml
@model Open.Logic.RoleClasses.RoleViewModel

@{
    ViewBag.Title = "Remove Role";
}

<h2>Do you want to delete Role?</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt></dt>
        <dd></dd>
        <dt> @Html.DisplayNameFor(model => model.UniqueId) </dt>
        <dd> @Html.DisplayFor(model => model.UniqueId) </dd>
        <dt> @Html.DisplayNameFor(model => model.Name) </dt>
        <dd> @Html.DisplayFor(model => model.Name) </dd>
        <dt> @Html.DisplayNameFor(model => model.Type) </dt>
        <dd> @Html.DisplayFor(model => model.Type) </dd>
        <dt> @Html.DisplayNameFor(model => model.Description) </dt>
        <dd> @Html.DisplayFor(model => model.Description) </dd>
        <dt> @Html.DisplayNameFor(model => model.IsActive) </dt>
        <dd> @Html.CheckBoxFor(model => model.IsActive, new { disabled = "disabled" }) </dd>
    </dl>
</div>
<p>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color" style="width: 50%">
            <input type="submit" value="Yes" class="btn btn-default" />  |  
            @Html.ActionLink("No", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</p>

project/Open/Soft/Views/Roles/Details.cshtml
@model Open.Logic.RoleClasses.RoleViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Role details</h2>

<div>
    <hr/>
    <dl class="dl-horizontal">
        <dt></dt>
        <dd></dd>
        <dt> @Html.DisplayNameFor(model => model.UniqueId) </dt>
        <dd> @Html.DisplayFor(model => model.UniqueId) </dd>
        <dt> @Html.DisplayNameFor(model => model.Name) </dt>
        <dd> @Html.DisplayFor(model => model.Name) </dd>
        <dt> @Html.DisplayNameFor(model => model.Type) </dt>
        <dd> @Html.DisplayFor(model => model.Type) </dd>
        <dt> @Html.DisplayNameFor(model => model.Description) </dt>
        <dd> @Html.DisplayFor(model => model.Description) </dd>
        <dt> @Html.DisplayNameFor(model => model.IsActive) </dt>
        <dd> @Html.CheckBoxFor(model => model.IsActive, new {disabled = "disabled"}) </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {id = Model.UniqueId}) |
    @Html.ActionLink("Delete", "Delete", new {id = Model.UniqueId}) |
    @Html.ActionLink("Back to List", "Index")
</p>

project/Open/Soft/Views/Roles/Edit.cshtml
@model Open.Logic.RoleClasses.RoleEditModel

@{
    ViewBag.Title = "Details";
}

<h2>Edit role details</h2>

@using (Html.BeginForm("Edit", "Roles", new { ID = Model.UniqueId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UniqueId)
        <div class="form-group">
            @Html.LabelFor(model => model.UniqueId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.UniqueId, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, Model.ActiveRoleTypes)
                @Html.ValidationMessageFor(model => model.ActiveRoleTypes, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

project/Open/Soft/Views/Roles/Index.cshtml
@model IEnumerable<Open.Logic.RoleClasses.RoleViewModel>
@{
    ViewBag.Title = "Roles";
}

<h2>Roles</h2>
<br />
<div>
    <span>
        @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-default" })
    </span>
</div>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UniqueId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UniqueId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.UniqueId }) |
                @Html.ActionLink("Details", "Details", new { id = item.UniqueId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.UniqueId })
            </td>
        </tr>
    }
</table>