project/Open/Soft/Controllers/PeopleController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Open.Archetypes.PartyClasses;
using Open.Archetypes.RoleClasses;
using Open.Data;
using Open.Logic.RoleClasses;

namespace Open.Soft.Controllers {
    [HandleError]
    public class PeopleController : Controller {
        public ActionResult Index() {
            var personViewModels = Parties.Instance.Where(person => person.IsActive)
                                          .Select(person => new PersonViewModel(person))
                                          .ToList();
            return View(personViewModels);
        }

        public ActionResult Create() { return View(new PersonEditModel()); }

        public ActionResult Refresh() {
            Database.RefreshData();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "Name, Surname, DateOfBirth, NewRoles")]
            PersonEditModel personEditModel) {
            if (!ModelState.IsValid) return View("Create", personEditModel);
            personEditModel.Create();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(string id) {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return View(new PersonEditModel(id));
        }

        public ActionResult Details(string id) {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return View(new PersonViewModel(id));
        }

        public ActionResult Delete(string id) {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return View(new PersonViewModel(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, FormCollection collection) {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var personEditModel = new PersonEditModel(id);
            personEditModel.Delete();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "UniqueId, Name, Surname, DateOfBirth, NewRoles")]
            PersonEditModel personEditModel) {
            if (!ModelState.IsValid) return View("Edit", personEditModel);
            personEditModel.Update(personEditModel.UniqueId);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveRole(string id, string roleid) {
            if (id == null || roleid == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var role = Roles.Find(roleid);
            if (role.IsPerformerId(id)) role.PerformerId = "";
            new RoleEntity().Update(role);
            return RedirectToAction("Edit", new { id });
        }
    }
}

project/Open/Soft/Views/People/Create.cshtml
@model Open.Logic.RoleClasses.PersonEditModel

@{
    ViewBag.Title = "Create person";
}

<h2>Create person details</h2>

@using (Html.BeginForm("Create", "People", new { ID = Model.UniqueId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Surname, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AvailableRoles, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Model.AvailableRoles.Any())
                {
                    @Html.ListBoxFor(model => model.NewRoles, Model.AvailableRoles, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessage("PartyRolesError", new { @class = "text-danger" })
                }
                else
                {
                    <div>No active roles</div>
                }
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

project/Open/Soft/Views/People/Delete.cshtml
@model Open.Logic.RoleClasses.PersonViewModel

@{
    ViewBag.Title = "Remove person";
}

<h2>Do you want to delete @Html.DisplayNameFor(model => model.Name) @Html.DisplayNameFor(model => model.Surname)?</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt> @Html.DisplayNameFor(model => model.UniqueId) </dt>
        <dd> @Html.DisplayFor(model => model.UniqueId) </dd>
        <dt> @Html.DisplayNameFor(model => model.Name) </dt>
        <dd> @Html.DisplayFor(model => model.Name) </dd>
        <dt> @Html.DisplayNameFor(model => model.Surname) </dt>
        <dd> @Html.DisplayFor(model => model.Surname) </dd>
        <dt> @Html.DisplayNameFor(model => model.DateOfBirth) </dt>
        <dd> @Html.DisplayFor(model => model.DateOfBirth) </dd>
        <dt> @Html.DisplayNameFor(model => model.RegistrationDate) </dt>
        <dd> @Html.DisplayFor(model => model.RegistrationDate) </dd>
        <dt> @Html.DisplayNameFor(model => model.Roles) </dt>
        <dd> @foreach (var role in Model.Roles) {
                 @Html.DisplayFor(name => role.Name)
                 <br/>
             }
         </dd>
    </dl>
</div>
<p>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div style="width: 50%">
            <input type="submit" value="Yes" class="btn btn-default" />  |
            @Html.ActionLink("No", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</p>

project/Open/Soft/Views/People/Details.cshtml
@model Open.Logic.RoleClasses.PersonViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Person details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt> @Html.DisplayNameFor(model => model.UniqueId) </dt>
        <dd> @Html.DisplayFor(model => model.UniqueId) </dd>
        <dt> @Html.DisplayNameFor(model => model.Name) </dt>
        <dd> @Html.DisplayFor(model => model.Name) </dd>
        <dt> @Html.DisplayNameFor(model => model.Surname) </dt>
        <dd> @Html.DisplayFor(model => model.Surname) </dd>
        <dt> @Html.DisplayNameFor(model => model.DateOfBirth) </dt>
        <dd> @Html.DisplayFor(model => model.DateOfBirth) </dd>
        <dt> @Html.DisplayNameFor(model => model.RegistrationDate) </dt>
        <dd> @Html.DisplayFor(model => model.RegistrationDate) </dd>
        <dt> @Html.DisplayNameFor(model => model.Roles) </dt>
        <dd> @foreach (var role in Model.Roles) {
                 @Html.DisplayFor(name => role.Name)
                 <br/>
             }
        </dd>
        @*<dt> @Html.DisplayNameFor(model => model.IsActive) </dt>
        <dd> @Html.CheckBoxFor(model => model.IsActive, new { disabled = "disabled" }) </dd>*@
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UniqueId }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.UniqueId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

project/Open/Soft/Views/People/Edit.cshtml
@model Open.Logic.RoleClasses.PersonEditModel

@{
    ViewBag.Title = "Edit person";
}

<h2>Edit person details</h2>

@using (Html.BeginForm("Edit", "People", new {ID = Model.UniqueId}, FormMethod.Post)) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.UniqueId)
        <div class="form-group">
            @Html.LabelFor(model => model.UniqueId, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DisplayFor(model => model.UniqueId, new {htmlAttributes = new {@class = "form-control"}})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Surname, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Surname, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new {htmlAttributes = new {@class = "form-control", text = Model.DateOfBirth}})
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PartyRoles, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @foreach (var role in Model.PartyRoles)
                {
                    <span style="padding-right: 1em">@Html.DisplayFor(name => role.Name)</span>
                    @Html.ActionLink("Remove", "RemoveRole", new {id = Model.UniqueId, roleId = role.UniqueId})
                    <br/>
                }
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AvailableRoles, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @if (Model.AvailableRoles.Any()) {
                    @Html.ListBoxFor(model => model.NewRoles, Model.AvailableRoles, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessage("PartyRolesError", new {@class = "text-danger"})
                } else {
                    <div>No active roles</div>
                }
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
}
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

project/Open/Soft/Views/People/Index.cshtml
@model IEnumerable<Open.Logic.RoleClasses.PersonViewModel>

@{
    ViewBag.Title = "People";
}

<h2>People</h2>
<br />
<div>
    <span>
        @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-default" })
    </span>
    <span>
        @Html.ActionLink("Update data", "Refresh", null, new { @class = "btn btn-default" })
    </span>
</div>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UniqueId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Roles)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UniqueId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationDate)
            </td>
            <td>
               @foreach (var role in item.Roles) {
                   @Html.DisplayFor(name => role.Name)
                   <br/>
               }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.UniqueId }) |
                @Html.ActionLink("Details", "Details", new { id = item.UniqueId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.UniqueId })
            </td>
        </tr>
    }
</table>